# Generated by Django 3.0.2 on 2020-02-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_receipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipe',
            new_name='Recipe',
        ),
    ]
