name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install docker-compose
      run: |
        python -m pip install --upgrade pip
        pip install docker-compose
    - name: Build the docker-compose stack
      run: docker-compose run app sh -c "python manage.py test && flake8"